apiVersion: batch/v1
kind: Job
metadata:
  name: epaxos-client
spec:
  parallelism: 5
  completions: 5
  template:
    metadata:
      name: epaxos-client
    spec:
      restartPolicy: Never
      containers:
        - name: client
          image: 0track/epaxos
          env:
            - name : TYPE
              value: "client"
            - name : MADDR
              valueFrom:
                configMapKeyRef:
                  name: epaxos-config
                  key: addr.master
            - name : MPORT
              valueFrom:
                configMapKeyRef:
                  name: epaxos-config
                  key: port.master
            - name : CLIENT_EXTRA_ARGS
              value: "-q 10000 -w 100 -c 0 -psize 2 -v"
